{% set name = "django-drf-filepond" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-drf-filepond-{{ version }}.tar.gz
  sha256: a32c46fd54982d88aeb4f3825973a194eb9d5d01b031c53bfe2770fc98895873

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=2.2.24
    - djangorestframework >=3.11.2
    - django-storages >=1.9.1
    - python >=3.6
    - requests >=2.20.1
    - six >=1.14.0
    - shortuuid >=0.5.0

test:
  imports:
    - django_drf_filepond
    - django_drf_filepond.migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ImperialCollegeLondon/django-drf-filepond
  summary: Filepond server app for Django REST Framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
