{% set name = "django-drf-filepond" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 77ed4ddd79dd9d5f5037ee0f54ed6b15ab256db3fc83a4f553a62cd38e5bba11

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - django >=2.2.25
    - djangorestframework >=3.12.4
    - django-storages >=1.9.1
    - python >={{ python_min }}
    - requests >=2.20.1
    - six >=1.14.0
    - shortuuid >=0.5.0

test:
  imports:
    - django_drf_filepond
    - django_drf_filepond.migrations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ImperialCollegeLondon/django-drf-filepond
  summary: Filepond server app for Django REST Framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
